;; -*- mode: eask; lexical-binding: t -*-

(package "copilot"
         "0.0.1"
         "An unofficial Copilot plugin for Emacs")

(website-url "https://github.com/copilot-emacs/copilot.el")
(keywords "convenience" "copilot")

(package-file "copilot.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "27.2")
(depends-on "editorconfig")
(depends-on "jsonrpc")
(depends-on "f")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
